a=["one","two","three"]
print(a)
b=a.copy()
print("copy\n",b)
a.append("four")
print(a)
print(b)
print("index on two",a.index("two"))
a.extend(["five","six"])
print(a)
print("reverse\n")
print(a)
a.sort()
print(a)