a=[3,4,2,4,6,5,7,8,9]
print("max=",max(a))
print("min=",min(a))
a.sort()
print("sorted list=",a)
a.reverse()
print("reversed list=",a)
a.sort()
print("sorted list=",a)
a.sort(reverse=True)
print("sorted in descending order=",a)
a.sort()
print("sorted in ascending order=",a)
print("2nd largest=",a[-2])
a.sort()
print("2nd smallest=",a[1])